### ISSUE TITLE
[TextFields] MDCBaseTextField.m loop on layoutSubviews

### ISSUE THREAD

**Issue by brennobemoura** [material-components/material-components-ios#10047]
## Reproduction steps

1. Create a form with more than one MDCOutlinedTextField.
2. Set text for text fields at the same time, so the animation would execute together.
2. Run application.

## Expected behavior

Open the form with no error.

## Actual behavior

The app is stuck on the loop at layoutSubviews.

## Platform (please complete the following information)

 - Device: iPhone Xr
 - OS: iOS 12.4

## Additional context

When I set the default text `self.emailField.text = "example@.com"` and `self.passwordField.text = "123"` one after other, the 
MDCBaseTextField stuck on layoutSubviews. But, if I set one, wait some time, and set the other, everything works great.

It doesn't happen all the time. On iOS 13, no error is reported.

**Comment by andrewoverton** [comment]
https://github.com/material-components/material-components-ios/issues/10041 was a very similar issue that has been fixed in the most recent release, which just landed this morning. I'm wondering if that fix also addresses your issue. Could you let me know if you can reproduce with the latest version? Thanks!

**Comment by brennobemoura** [comment]
@andrewoverton I will test and if it isn't resolved, I'll open this bug report. Thanks!
